name: Build and test check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_run:
    name: Build project and run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Print trigger event and user
      run: echo "Trigger event - ${{ github.event_name }}, User - ${{ github.actor }}"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install npm dependencies
      run: npm install

    - name: Build project 
      run: npm run build

    - name: Run tests
      working-directory: client
      run: npm test